name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pre-commit
      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --all-files
      - name: Run tests
        run: |
          coverage run -m pytest -q
          coverage xml
