name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage coverage-badge
      - name: Run tests
        run: |
          coverage run -m pytest -q
      - name: Smoke tests
        if: github.event_name == 'schedule'
        run: pytest tests/test_logic.py tests/test_flags.py
      - name: Publish coverage badge
        if: github.event_name != 'pull_request'
        run: |
          coverage xml
          coverage-badge -o coverage.svg -f
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add coverage.svg README.md
          git commit -m "Update coverage badge" || exit 0
          git push
