name: Build and Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
      - uses: snok/install-poetry@v1
      - name: Install deps
        run: poetry install --no-interaction --with dev --sync
      - name: Build docs
        run: |
          poetry run sphinx-build -b html -W docs docs/_build/html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html
      - uses: actions/deploy-pages@v2
