name: Update Changelog and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update CHANGELOG
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PREV_TAG=$(git describe --tags --abbrev=0 "$TAG"^ 2>/dev/null || echo "")
          DATE=$(date +%Y-%m-%d)
          echo "## [$TAG] - $DATE" > new_changelog
          if [ -n "$PREV_TAG" ]; then
            git log "$PREV_TAG"..HEAD --pretty=format:"- %s" >> new_changelog
          else
            git log --pretty=format:"- %s" >> new_changelog
          fi
          echo >> new_changelog
          cat CHANGELOG.md >> new_changelog
          mv new_changelog CHANGELOG.md

      - name: Commit CHANGELOG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for $TAG" || echo "no changes"
          git push

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
