name: Daily Smoke
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run smoke tests
        run: pytest -q tests || true
      - name: Notify Slack
        if: always()
        run: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Smoke tests completed"}' "$SLACK_WEBHOOK_URL"
          fi
      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: '587'
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Smoke tests
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <noreply@example.com>
          body: Smoke tests completed.
